package main

import (
	"context"
	"encoding/json"
	"errors"
	"log"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"
	"github.com/joho/godotenv"
	"github.com/prometheus/client_golang/prometheus/promhttp"
	httpSwagger "github.com/swaggo/http-swagger"

	_ "gotrade/account-service/docs" // docs is generated by Swag CLI
	"gotrade/account-service/internal/handler"
	"gotrade/account-service/internal/platform/database"
	"gotrade/account-service/internal/repository"
	"gotrade/account-service/internal/usecase"
)

// @title Account Service API
// @version 1.0
// @description This is the API for the Account Service of GoTrade.
// @host localhost:8080
// @BasePath /api/account
// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization
func main() {
	_ = godotenv.Load() // Load .env file if it exists

	port := os.Getenv("APP_PORT")
	if port == "" {
		port = "8084"
	}

	postgresURL := os.Getenv("POSTGRES_URL")
	if postgresURL == "" {
		log.Fatal("POSTGRES_URL environment variable is not set")
	}

	jwtSecret := os.Getenv("JWT_SECRET")
	if jwtSecret == "" {
		log.Fatal("JWT_SECRET environment variable is not set")
	}

	// Initialize database
	dbPool, err := database.NewPostgresPool(postgresURL)
	if err != nil {
		log.Fatalf("Failed to connect to PostgreSQL: %v", err)
	}
	defer dbPool.Close()

	if err := database.InitDatabase(dbPool); err != nil {
		log.Fatalf("Failed to initialize database: %v", err)
	}

	// Setup dependencies
	accountRepo := repository.NewPostgresAccountRepository(dbPool)
	accountUsecase := usecase.NewAccountUsecase(accountRepo)
	accountHandler := handler.NewAccountHandler(accountUsecase)

	// Setup router
	r := chi.NewRouter()
	r.Use(middleware.Logger)
	r.Use(middleware.Recoverer)

	// Swagger
	r.Get("/swagger/*", httpSwagger.WrapHandler)

	// Health and Metrics
	r.Get("/health", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		json.NewEncoder(w).Encode(map[string]string{"status": "ok"})
	})
	r.Handle("/metrics", promhttp.Handler())

	// Protected routes
	r.Group(func(r chi.Router) {
		r.Use(handler.JWTAuthMiddleware(jwtSecret))
		r.Get("/", accountHandler.GetAccount)
		r.Post("/transfer", accountHandler.FundTransfer)
	})

	// Server setup
	server := &http.Server{
		Addr:    ":" + port,
		Handler: r,
	}

	// Graceful shutdown
	go func() {
		log.Printf("Server starting on port %s", port)
		if err := server.ListenAndServe(); err != nil && !errors.Is(err, http.ErrServerClosed) {
			log.Fatalf("Could not listen on %s: %v\n", port, err)
		}
	}()

	stop := make(chan os.Signal, 1)
	signal.Notify(stop, os.Interrupt, syscall.SIGTERM)
	<-stop

	log.Println("Shutting down server...")

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	if err := server.Shutdown(ctx); err != nil {
		log.Fatalf("Server shutdown failed: %v", err)
	}

	log.Println("Server gracefully stopped")
}

