package main

import (
	"context"
	"encoding/json"
	"log"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"
	"github.com/joho/godotenv"
	"github.com/prometheus/client_golang/prometheus/promhttp"
	httpSwagger "github.com/swaggo/http-swagger"

	_ "gotrade/order-service/docs" // docs is generated by Swag CLI
	"gotrade/order-service/internal/handler"
	"gotrade/order-service/internal/platform/database"
	"gotrade/order-service/internal/platform/messaging"
	"gotrade/order-service/internal/repository"
	"gotrade/order-service/internal/usecase"
)

// @title Order Service API
// @version 1.0
// @description This is the API for the Order Service of GoTrade.
// @host localhost:8080
// @BasePath /api/orders
// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization
func main() {
	_ = godotenv.Load()

	port := os.Getenv("APP_PORT")
	if port == "" {
		port = "8083"
	}

	postgresURL := os.Getenv("POSTGRES_URL")
	if postgresURL == "" {
		log.Fatal("POSTGRES_URL environment variable is not set")
	}

	redisURL := os.Getenv("REDIS_URL")
	if redisURL == "" {
		log.Fatal("REDIS_URL environment variable is not set")
	}

	jwtSecret := os.Getenv("JWT_SECRET")
	if jwtSecret == "" {
		log.Fatal("JWT_SECRET environment variable is not set")
	}

	// Initialize database
	dbPool, err := database.NewPostgresPool(postgresURL)
	if err != nil {
		log.Fatalf("Failed to connect to PostgreSQL: %v", err)
	}
	defer dbPool.Close()

	if err := database.InitDatabase(dbPool); err != nil {
		log.Fatalf("Failed to initialize database: %v", err)
	}

	// Initialize publisher
	publisher, err := messaging.NewRedisPublisher(redisURL)
	if err != nil {
		log.Fatalf("Failed to connect to Redis: %v", err)
	}
	defer publisher.Close()

	// Setup dependencies
	orderRepo := repository.NewPostgresOrderRepository(dbPool)
	orderUsecase := usecase.NewOrderUsecase(orderRepo, publisher, dbPool)
	orderHandler := handler.NewOrderHandler(orderUsecase)

	// Start outbox poller
	pollerCtx, cancelPoller := context.WithCancel(context.Background())
	defer cancelPoller()
	go orderUsecase.StartOutboxPolling(pollerCtx)

	// Setup router
	r := chi.NewRouter()
	r.Use(middleware.Logger)
	r.Use(middleware.Recoverer)

	// Swagger
	r.Get("/swagger/*", httpSwagger.WrapHandler)

	// Health and Metrics
	r.Get("/health", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		json.NewEncoder(w).Encode(map[string]string{"status": "ok"})
	})
	r.Handle("/metrics", promhttp.Handler())

	// Protected routes
	r.Group(func(r chi.Router) {
		r.Use(handler.JWTAuthMiddleware(jwtSecret))
		r.Post("/", orderHandler.PlaceOrder)
		r.Get("/", orderHandler.GetOrders)
		r.Delete("/{orderID}", orderHandler.CancelOrder)
	})

	// Start server
	server := &http.Server{
		Addr:    ":" + port,
		Handler: r,
	}

	go func() {
		log.Printf("Server starting on port %s", port)
		if err := server.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			log.Fatalf("Could not listen on %s: %v\n", port, err)
		}
	}()

	// Graceful shutdown
	stop := make(chan os.Signal, 1)
	signal.Notify(stop, os.Interrupt, syscall.SIGTERM)
	<-stop

	log.Println("Shutting down server...")
	cancelPoller() // Stop the outbox poller

	shutdownCtx, shutdownCancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer shutdownCancel()

	if err := server.Shutdown(shutdownCtx); err != nil {
		log.Fatalf("Server shutdown failed: %v", err)
	}

	log.Println("Server gracefully stopped")
}

